Negro
SussyRaider/readme pull request #25
Opened 2022-01-15 14:31 UTC by Sueqkjs

test

2022-01-15 14:35 UTC, AlphaNull16299 commented
まーじしていいのこれ

2022-01-15 14:37 UTC, Sueqkjs commented
今test中、なんか動いてねえ

2022-01-15 14:41 UTC, Sueqkjs commented
寝るわ

2022-01-15 14:47 UTC, Sueqkjs reviewed
aanan

2022-01-15 14:47 UTC, AlphaNull16299 commented
あんまり意味感じないんだけどこれは何

2022-01-15 22:33 UTC, waki285 requested changes
setup-node v2希望

2022-01-15 22:33 UTC, waki285 commented on .github/workflows/reviewdog.yml
> +        uses: actions/setup-node@v1
```suggestion
        uses: actions/setup-node@v2
```

2022-01-15 23:05 UTC, mopeneko commented on .github/workflows/reviewdog.yml
> +          node-version: '15'
Node.jsのLTSは16なので、16を推奨したいですね
```suggestion
          node-version: '16'
```

2022-01-15 23:21 UTC, waki285 commented on .github/workflows/reviewdog.yml
> +          node-version: '15'
:iine:

2022-01-15 23:23 UTC, waki285 reviewed
追加で、prのときの発動条件をmainブランチへのprに限定する。

2022-01-15 23:23 UTC, waki285 commented on .github/workflows/reviewdog.yml
> +on: [pull_request]
```suggestion
on: 
  pull_request:
    branches: 
      - main
```

2022-01-15 23:33 UTC, Sueqkjs commented
ありがてえ.....

2022-01-15 23:51 UTC, Sueqkjs commented
`reviewdog: environment variable $REVIEWDOG_GITHUB_API_TOKEN is not set`
セットしたのにセットされてないってどういうことやねん、まあ直すけど

2022-01-15 23:56 UTC, mopeneko commented
`github_token: ${{ secrets.GITHUB_TOKEN }}` だったような

2022-01-16 00:00 UTC, Sueqkjs commented
いや、それがなかったみたいだから自前でtoken生成してセットしてる

2022-01-16 00:01 UTC, mopeneko commented
GitHubを殺す

2022-01-16 00:02 UTC, Sueqkjs commented
なんか無理だったｗｗｗｗｗワークフローむずいな

2022-01-16 00:04 UTC, Sueqkjs commented
https://github.com/tsuyoshicho/action-textlint/blob/7d9feda309dd2afc14d95b7a108dad1508d06479/script.sh#L30
うーんinputに設定してるんだけどなー謎い

2022-01-16 00:05 UTC, mopeneko commented
github_tokenじゃなくてGITHUB_TOKENならいけるとかない？

2022-01-16 00:05 UTC, Sueqkjs commented
やってみるわ

2022-01-16 00:09 UTC, mopeneko commented
いや、そっちじゃなくて、
`github_token: ${{ secrets.GITHUB_TOKEN }}`
って感じで

2022-01-16 00:10 UTC, mopeneko commented
あ、それだとwrite権限がないのか

2022-01-16 00:12 UTC, mopeneko commented
マージ先リポジトリの方にsecretが追加されてないんじゃない？

2022-01-16 00:17 UTC, Sueqkjs commented
追加してみた

2022-01-16 00:18 UTC, mopeneko commented
GitHubを殺す

2022-01-16 00:21 UTC, Sueqkjs commented
やべえ謎すぎる、一回飯食うわ

2022-01-16 00:21 UTC, Sueqkjs commented
![FC01B633-0299-4783-851F-C065F9DBD300](https://user-images.githubusercontent.com/68449029/149642342-c0c6ba66-4689-451a-ae71-587a59e010bd.jpeg)

2022-01-16 00:31 UTC, mopeneko commented
その場合secrets.TOKENじゃないとアクセスできなさそう

2022-01-16 00:32 UTC, Sueqkjs commented
えcase関係あるのね、やってみる。

2022-01-16 00:36 UTC, Sueqkjs commented
![F69988CD-E1B8-48D3-9B7D-C90C4E5058DC](https://user-images.githubusercontent.com/68449029/149642722-6c441e95-3b83-4bf0-ba89-8045da747817.jpeg)
actionsなぞすぎ

2022-01-16 00:55 UTC, mopeneko commented
🤔

2022-01-16 00:58 UTC, Sueqkjs commented
完全に理解した

2022-01-16 01:00 UTC, waki285 requested changes
別prとして提出しよう

2022-01-16 01:02 UTC, Sueqkjs commented
普通に間違えてた

2022-01-16 01:03 UTC, mopeneko commented
![image](https://user-images.githubusercontent.com/26901342/149643323-cdfc6789-8e85-4318-a0e7-bd44c90c44ce.png)

2022-01-16 01:04 UTC, Sueqkjs commented
要するにpull_request_targetにしようってことじゃないの?

2022-01-16 01:05 UTC, mopeneko commented
y

2022-01-16 01:06 UTC, waki285 approved these changes
:iine:

2022-01-16 01:10 UTC, Sueqkjs commented
なんか発火しないぞ

2022-01-16 01:19 UTC, mopeneko commented
マージ後じゃないと発火しないと思う
マージ前に発火する仕様だとやり方次第でsecret盗み放題なので

2022-01-16 01:23 UTC, Sueqkjs commented
マジか....とりあえずマージする

2022-01-16 01:23 UTC, merged